# Platform Detection
if(CMAKE_CXX_BYTE_ORDER STREQUAL BIG_ENDIAN)
	set(ENGINE_PLATFORM_BIG_ENDIAN TRUE CACHE BOOL "")

elseif(CMAKE_CXX_BYTE_ORDER STREQUAL LITTLE_ENDIAN)
	set(ENGINE_PLATFORM_LITTLE_ENDIAN TRUE CACHE BOOL "")
endif()



if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
	set(ENGINE_PLATFORM_WINDOWS TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
	set(ENGINE_PLATFORM_ANDROID TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
	set(ENGINE_PLATFORM_LINUX TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Emscripten")
	set(ENGINE_PLATFORM_EMSCRIPTEN TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
	set(ENGINE_PLATFORM_MACOSX TRUE CACHE BOOL "")	

elseif(CMAKE_SYSTEM_NAME STREQUAL "iOS")
	set(ENGINE_PLATFORM_IOS TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "tvOS")
	set(ENGINE_PLATFORM_TVOS TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "watchOS")
	set(ENGINE_PLATFORM_WATCHOS TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "MSYS")
	set(ENGINE_PLATFORM_MSYS TRUE CACHE BOOL "")

elseif(CMAKE_SYSTEM_NAME STREQUAL "CYGWIN")
	set(ENGINE_PLATFORM_CYGWIN TRUE CACHE BOOL "")

else()
	message(FATAL_ERROR "Unknown platform")
endif()

if(UNIX)
	set(ENGINE_PLATFORM_UNIX TRUE CACHE BOOL "")
endif()

if(APPLE)
	set(ENGINE_PLATFORM_APPLE TRUE CACHE BOOL "")
endif()




if(ENGINE_PLATFORM_WINDOWS)

	if(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
		set(ENGINE_CPU_X86_64 TRUE CACHE BOOL "")

	elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "ARM64")
		set(ENGINE_CPU_ARM64 TRUE CACHE BOOL "")

	else()
		set(ENGINE_CPU_UNKNOWN TRUE CACHE BOOL "")
	endif()

elseif(ENGINE_PLATFORM_MACOSX)

	if(CMAKE_APPLE_SILICON_PROCESSOR STREQUAL "x86_64")
		set(ENGINE_CPU_X86_64 TRUE CACHE BOOL "")
	
	elseif(CMAKE_APPLE_SILICON_PROCESSOR STREQUAL "arm64")
		set(ENGINE_CPU_ARM64 TRUE CACHE BOOL "")

	else()
		set(ENGINE_CPU_UNKNOWN TRUE CACHE BOOL "")
	endif()

elseif(ENGINE_PLATFORM_UNIX)

	if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64")
		set(ENGINE_CPU_X86_64 TRUE CACHE BOOL "")

	elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
		set(ENGINE_CPU_ARM64 TRUE CACHE BOOL "")

	else()
		set(ENGINE_CPU_UNKNOWN TRUE CACHE BOOL "")
	endif()

else()
	set(ENGINE_CPU_UNKNOWN TRUE CACHE BOOL "")
endif()






function(define_platform_info target)
	
	target_compile_definitions(${target} PRIVATE

			ENGINE_PLATFORM_BIG_ENDIAN=$<BOOL:${ENGINE_PLATFORM_BIG_ENDIAN}>
			ENGINE_PLATFORM_LITTLE_ENDIAN=$<BOOL:${ENGINE_PLATFORM_LITTLE_ENDIAN}>
			
			ENGINE_PLATFORM_WINDOWS=$<BOOL:${ENGINE_PLATFORM_WINDOWS}>
			ENGINE_PLATFORM_ANDROID=$<BOOL:${ENGINE_PLATFORM_ANDROID}>
			ENGINE_PLATFORM_LINUX=$<BOOL:${ENGINE_PLATFORM_LINUX}>
			ENGINE_PLATFORM_EMSCRIPTEN=$<BOOL:${ENGINE_PLATFORM_EMSCRIPTEN}>
			ENGINE_PLATFORM_MACOSX=$<BOOL:${ENGINE_PLATFORM_MACOSX}>
			ENGINE_PLATFORM_IOS=$<BOOL:${ENGINE_PLATFORM_IOS}>
			ENGINE_PLATFORM_TVOS=$<BOOL:${ENGINE_PLATFORM_TVOS}>
			ENGINE_PLATFORM_WATCHOS=$<BOOL:${ENGINE_PLATFORM_WATCHOS}>
			ENGINE_PLATFORM_MSYS=$<BOOL:${ENGINE_PLATFORM_MSYS}>
			ENGINE_PLATFORM_CYGWIN=$<BOOL:${ENGINE_PLATFORM_CYGWIN}>
			ENGINE_PLATFORM_UNIX=$<BOOL:${ENGINE_PLATFORM_UNIX}>
			ENGINE_PLATFORM_APPLE=$<BOOL:${ENGINE_PLATFORM_APPLE}>

			ENGINE_CPU_X86_64=$<BOOL:${ENGINE_CPU_X86_64}>
			ENGINE_CPU_ARM64=$<BOOL:${ENGINE_CPU_ARM64}>
			ENGINE_CPU_UNKNOWN=$<BOOL:${ENGINE_CPU_UNKNOWN}>
	)

endfunction()



message(STATUS "-PLATFORM         = ${CMAKE_SYSTEM_NAME}")

if(ENGINE_CPU_X86_64)
	message(STATUS "-CPU              = X86_64")
elseif(ENGINE_CPU_ARM64)
	message(STATUS "-CPU              = ARM64")
else()
	message(STATUS "-CPU              = Unknown")
endif()

if(ENGINE_PLATFORM_LITTLE_ENDIAN)
	message(STATUS "-ENDIANNESS       = Little")
else()
	message(STATUS "-ENDIANNESS       = Big")
endif()
